name: Check code style

on: [push]

jobs:
  check-style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ code
        uses: jidicula/clang-format-action@v3.1.0
        with:
          clang-format-version: '11'
          check-path: '.'
